upgrade all dependencies but "extract-loader", its "1.0.2" breaks with ```  error  in ./~/semantic-ui-css/semantic.css
Module build failed: /Users/truongsinh/Development/truongsinh.pro/node_modules/semantic-ui-css/semantic.css:1
exports = module.exports = require("../css-loader/lib/css-base.js")();
                                                                   ^

TypeError: require(...) is not a function
    at /Users/truongsinh/Development/truongsinh.pro/node_modules/semantic-ui-css/semantic.css:1:68
    at Script.runInContext (vm.js:74:29)
    at Script.runInNewContext (vm.js:80:15)
    at Object.extractLoader (/Users/truongsinh/Development/truongsinh.pro/node_modules/extract-loader/lib/extractLoader.js:88:12)

 @ ./src/pages/index.tsx 46:292-331
```